Feature/intents
resuelve/flowex pull request #1
Opened 2017-12-22 18:43 UTC by alanraul

2017-12-22 19:03 UTC, oscarolbe requested changes

2017-12-22 19:03 UTC, oscarolbe commented on lib/flowex.ex
> +      {:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
no puedes usar un guard ???
```
{:ok, %HTTPoison.Response{status_code: status_code, body: body}} when status_code in [200, 400, ...] ->
```

2017-12-22 19:03 UTC, oscarolbe commented on lib/flowex/api/intents.ex
> +  def get(id) do
specs y docs

2017-12-23 16:01 UTC, oscarolbe approved these changes

2017-12-26 15:10 UTC, alvarolizama approved these changes

2017-12-26 15:10 UTC, merged